[package]
name = "jlang"
version = "0.1.0"
authors = ["Nathan Hare <me@laspruca.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.5"
env_logger = "0.8.3"
log = "0.4.14"
console = "0.14.1"
